# Generated by Django 2.2.6 on 2019-10-13 06:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20191013_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 13, 0, 0, tzinfo=utc)),
        ),
    ]
